In [24]:
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("credit_risk_dataset.csv")

In [25]:

df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_grade                  32581 non-null  str
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  str
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.0 MB

In [26]:
df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [27]:
df["person_emp_length"] = df["person_emp_length"].fillna(df["person_emp_length"].median())

In [28]:
df["loan_int_rate"] = df["loan_int_rate"].fillna(df["loan_int_rate"].median())

In [29]:
df.dropna(inplace=True)

In [30]:
df.shape

(32581, 12)

In [31]:
df["loan_status"].value_counts()

loan_status
0    25473
1     7108
Name: count, dtype: int64

In [32]:
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [34]:
df["cb_person_default_on_file"] = df["cb_person_default_on_file"].replace({
    "Y":1,
    "N":0
})

In [35]:
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,1,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,0,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,0,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,0,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,0,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,0,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,0,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,0,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,0,30

In [36]:
df["loan_grade"] = df["loan_grade"].map({
    "A":1,
    "B":2,
    "C":3,
    "D":4,
    "E":5,
    "F":6,
    "G":7
})

In [37]:
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,4,35000,16.02,1,0.59,1,3
1,21,9600,OWN,5.0,EDUCATION,2,1000,11.14,0,0.10,0,2
2,25,9600,MORTGAGE,1.0,MEDICAL,3,5500,12.87,1,0.57,0,3
3,23,65500,RENT,4.0,MEDICAL,3,35000,15.23,1,0.53,0,2
4,24,54400,RENT,8.0,MEDICAL,3,35000,14.27,1,0.55,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,3,5800,13.16,0,0.11,0,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,1,17625,7.49,0,0.15,0,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,2,35000,10.99,1,0.46,0,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,2,15000,11.48,0,0.10,0,26
32580,66,42000,RENT,2.0,MEDICAL,2,6475,9.99,0,0.15,0,30

In [38]:
df["loan_grade"].value_counts()

loan_grade
1    10777
2    10451
3     6458
4     3626
5      964
6      241
7       64
Name: count, dtype: int64

In [40]:
df = pd.get_dummies(
    df,
    columns = ["person_home_ownership"],
    drop_first=True
    )

In [41]:
df

,person_age,person_income,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT
0,22,59000,123.0,PERSONAL,4,35000,16.02,1,0.59,1,3,False,False,True
1,21,9600,5.0,EDUCATION,2,1000,11.14,0,0.10,0,2,False,True,False
2,25,9600,1.0,MEDICAL,3,5500,12.87,1,0.57,0,3,False,False,False
3,23,65500,4.0,MEDICAL,3,35000,15.23,1,0.53,0,2,False,False,True
4,24,54400,8.0,MEDICAL,3,35000,14.27,1,0.55,1,4,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,1.0,PERSONAL,3,5800,13.16,0,0.11,0,30,False,False,False
32577,54,120000,4.0,PERSONAL,1,17625,7.49,0,0.15,0,19,False,False,False
32578,65,76000,3.0,HOMEIMPROVEMENT,2,35000,10.99,1,0.46,0,28,False,False,True
32579,56,150000,5.0,PERSONAL,2,15000,11.48,0,0.10,0,26,False,False,False
32580,66,42000,2.0,MEDICAL,2,6475,9.99,0,0.15,0,30,False,False,True

In [46]:
df = df.astype({
    "person_home_ownership_OTHER": int,
    "person_home_ownership_OWN": int,
    "person_home_ownership_RENT": int,
    "loan_intent_EDUCATION": int,
    "loan_intent_HOMEIMPROVEMENT": int,
    "loan_intent_MEDICAL": int,
    "loan_intent_PERSONAL": int,
    "loan_intent_VENTURE": int
})

In [43]:
df

,person_age,person_income,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT
0,22,59000,123.0,PERSONAL,4,35000,16.02,1,0.59,1,3,0,0,1
1,21,9600,5.0,EDUCATION,2,1000,11.14,0,0.10,0,2,0,1,0
2,25,9600,1.0,MEDICAL,3,5500,12.87,1,0.57,0,3,0,0,0
3,23,65500,4.0,MEDICAL,3,35000,15.23,1,0.53,0,2,0,0,1
4,24,54400,8.0,MEDICAL,3,35000,14.27,1,0.55,1,4,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,1.0,PERSONAL,3,5800,13.16,0,0.11,0,30,0,0,0
32577,54,120000,4.0,PERSONAL,1,17625,7.49,0,0.15,0,19,0,0,0
32578,65,76000,3.0,HOMEIMPROVEMENT,2,35000,10.99,1,0.46,0,28,0,0,1
32579,56,150000,5.0,PERSONAL,2,15000,11.48,0,0.10,0,26,0,0,0
32580,66,42000,2.0,MEDICAL,2,6475,9.99,0,0.15,0,30,0,0,1

In [44]:
df = pd.get_dummies(df,
                    columns =["loan_intent"],
                    drop_first = True)

In [47]:
df

,person_age,person_income,person_emp_length,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE
0,22,59000,123.0,4,35000,16.02,1,0.59,1,3,0,0,1,0,0,0,1,0
1,21,9600,5.0,2,1000,11.14,0,0.10,0,2,0,1,0,1,0,0,0,0
2,25,9600,1.0,3,5500,12.87,1,0.57,0,3,0,0,0,0,0,1,0,0
3,23,65500,4.0,3,35000,15.23,1,0.53,0,2,0,0,1,0,0,1,0,0
4,24,54400,8.0,3,35000,14.27,1,0.55,1,4,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,1.0,3,5800,13.16,0,0.11,0,30,0,0,0,0,0,0,1,0
32577,54,120000,4.0,1,17625,7.49,0,0.15,0,19,0,0,0,0,0,0,1,0
32578,65,76000,3.0,2,35000,10.99,1,0.46,0,28,0,0,1,0,1,0,0,0
32579,56,150000,5.0,2,15000,11.48,0,0.10,0,26,0,0,0,0,0,0,1,0
32580,66,42000,2.0,2,6475,9.99,0,0.15,0,30,0,0,1,0,0,1,0,0

In [101]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,classification_report,recall_score,f1_score

In [52]:
predictors = [
    "person_age",
    "person_income",
    "person_emp_length",
    "loan_grade",
    "loan_amnt",
    "loan_int_rate",
    "loan_percent_income",
    "cb_person_default_on_file",
    "cb_person_cred_hist_length",
    "person_home_ownership_OTHER",
    "person_home_ownership_OWN",
    "person_home_ownership_RENT",
    "loan_intent_EDUCATION",
    "loan_intent_HOMEIMPROVEMENT",
    "loan_intent_MEDICAL",
    "loan_intent_PERSONAL",
    "loan_intent_VENTURE"
]

X = df[predictors]
y = df["loan_status"]

In [54]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

In [55]:
X_train.shape

(26064, 17)

In [56]:
X_test.shape

(6517, 17)

In [58]:
y_train.shape

(26064,)

In [67]:
y_test

6616     0
21802    0
31886    0
17799    0
5207     0
        ..
26943    1
15537    0
2834     0
13151    0
9938     0
Name: loan_status, Length: 6517, dtype: int64

In [78]:
model = LogisticRegression(
    max_iter = 1000,
    class_weight = "balanced"
)
model.fit(X_train,y_train)

C:\Users\vpree\Desktop\ml-credit\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced', max_iter=1000)

In [79]:
prediction = model.predict(X_test)

In [80]:
prediction

array([0, 0, 0, ..., 0, 1, 0], shape=(6517,))

In [81]:
accuracy_score(prediction,y_test)

0.7561761546723953

In [82]:
precision_score(y_test,prediction)

0.4649895178197065

In [83]:
# df = pd.DataFrame(classification_report(y_test,prediction))
# df
classification_report(y_test,prediction)

'              precision    recall  f1-score   support\n\n           0       0.92      0.75      0.83      5095\n           1       0.46      0.78      0.58      1422\n\n    accuracy                           0.76      6517\n   macro avg       0.69      0.76      0.71      6517\nweighted avg       0.82      0.76      0.77      6517\n'

In [85]:
results = X_test.copy()
results["actual"] = y_test
results["prediction"] = prediction

In [86]:
results

,person_age,person_income,person_emp_length,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,actual,prediction
6616,22,50000,6.0,2,6000,11.89,0.12,0,2,0,0,1,0,0,0,1,0,0,0
21802,32,52000,0.0,1,7125,7.49,0.14,0,10,0,0,1,0,0,0,1,0,0,0
31886,37,205000,3.0,2,18000,10.39,0.09,0,14,0,0,0,1,0,0,0,0,0,0
17799,26,100000,5.0,2,24000,10.99,0.24,0,4,0,0,0,0,0,0,0,0,0,0
5207,23,44340,0.0,3,3000,12.98,0.07,1,3,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26943,30,43992,2.0,4,15000,13.24,0.34,0,7,0,0,1,0,0,0,1,0,1,1
15537,26,75531,3.0,4,15000,16.49,0.20,0,4,0,0,1,0,0,0,1,0,0,1
2834,22,58000,6.0,2,3000,11.83,0.05,0,2,0,0,1,1,0,0,0,0,0,0
13151,24,89000,8.0,3,25000,13.11,0.28,1,3,0,0,0,0,0,1,0,0,0,1
9938,23,65000,0.0,3,8500,15.23,0.13,1,3,0,0,0,1,0,0,0,0,0,0

In [90]:
results[(results["actual"]==0) & (results["prediction"]==1)]

,person_age,person_income,person_emp_length,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,actual,prediction
2543,24,30000,1.0,2,3000,10.37,0.10,0,2,0,0,1,0,0,0,1,0,0,1
29839,41,75000,15.0,4,4000,16.29,0.05,1,12,0,0,1,0,0,0,1,0,0,1
2388,26,52000,6.0,3,2500,14.82,0.05,1,2,0,0,1,0,0,0,0,0,0,1
2833,23,35000,7.0,2,12000,12.42,0.34,0,2,0,0,0,0,0,0,0,0,0,1
28091,32,59363,2.0,3,6000,13.22,0.10,1,6,0,0,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13594,24,56000,0.0,2,12800,10.99,0.23,0,4,0,0,1,1,0,0,0,0,0,1
23138,27,60000,3.0,5,5000,16.45,0.08,0,6,0,0,0,0,0,0,1,0,0,1
1810,22,24702,4.0,3,2000,13.23,0.08,1,4,0,0,1,1,0,0,0,0,0,1
15537,26,75531,3.0,4,15000,16.49,0.20,0,4,0,0,1,0,0,0,1,0,0,1
13151,24,89000,8.0,3,25000,13.11,0.28,1,3,0,0,0,0,0,1,0,0,0,1

In [91]:
from sklearn.ensemble import RandomForestClassifier

In [93]:
reg = RandomForestClassifier(
    n_estimators = 100,
    random_state = 42,
    class_weight = "balanced"
)

In [94]:
reg.fit(X_train,y_train)
prediction1 = reg.predict(X_test)
prediction1

array([0, 0, 0, ..., 0, 0, 0], shape=(6517,))

In [104]:
accuracy_score(y_test, prediction1)

0.9291084854994629

In [105]:
precision_score(y_test, prediction1)

0.9152249134948097

In [106]:
recall_score(y_test, prediction1)

0.7440225035161744

In [107]:
f1_score(y_test, prediction1)

0.8207913110938713

In [108]:
results["prediction"] = prediction1

In [109]:
results

,person_age,person_income,person_emp_length,loan_grade,loan_amnt,loan_int_rate,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,person_home_ownership_OTHER,person_home_ownership_OWN,person_home_ownership_RENT,loan_intent_EDUCATION,loan_intent_HOMEIMPROVEMENT,loan_intent_MEDICAL,loan_intent_PERSONAL,loan_intent_VENTURE,actual,prediction
6616,22,50000,6.0,2,6000,11.89,0.12,0,2,0,0,1,0,0,0,1,0,0,0
21802,32,52000,0.0,1,7125,7.49,0.14,0,10,0,0,1,0,0,0,1,0,0,0
31886,37,205000,3.0,2,18000,10.39,0.09,0,14,0,0,0,1,0,0,0,0,0,0
17799,26,100000,5.0,2,24000,10.99,0.24,0,4,0,0,0,0,0,0,0,0,0,0
5207,23,44340,0.0,3,3000,12.98,0.07,1,3,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26943,30,43992,2.0,4,15000,13.24,0.34,0,7,0,0,1,0,0,0,1,0,1,1
15537,26,75531,3.0,4,15000,16.49,0.20,0,4,0,0,1,0,0,0,1,0,0,0
2834,22,58000,6.0,2,3000,11.83,0.05,0,2,0,0,1,1,0,0,0,0,0,0
13151,24,89000,8.0,3,25000,13.11,0.28,1,3,0,0,0,0,0,1,0,0,0,0
9938,23,65000,0.0,3,8500,15.23,0.13,1,3,0,0,0,1,0,0,0,0,0,0

In [110]:
classification_report(y_test,prediction1)

'              precision    recall  f1-score   support\n\n           0       0.93      0.98      0.96      5095\n           1       0.92      0.74      0.82      1422\n\n    accuracy                           0.93      6517\n   macro avg       0.92      0.86      0.89      6517\nweighted avg       0.93      0.93      0.93      6517\n'

In [111]:
import joblib

In [112]:
rf_model = reg
joblib.dump(rf_model,"credit_default_rf_model.pkl")

['credit_default_rf_model.pkl']

In [114]:
joblib.dump(prediction1,"predictor_columns.pkl")

['predictor_columns.pkl']